#Verification pipeline
trigger:
  branches:
    - main

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformCLI@0
  displayName: 'Verify IaC Pipeline'
  inputs:
    command: 'fmt'
    commandOptions: '-diff -recursive'
    allowTelemetryCollection: true

- script: |
    curl \
      -X POST \
      -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
      -H "Accept: application/vnd.github.v3+json" \
      "https://api.github.com/repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches"
  displayName: 'Tigger Scan Project'
  condition: always()
